import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopOfHomePage from "./component/top/TopOfHomePage";
import NavBar from "./component/Nav/NavBar";
import AuthProvider from "@/src/components/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navigationData = [
  {
    title: 'Home',
    href: '/'
  },
  {
    title: 'Self-Projects',
    href: '/projects'
  }
]

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        <TopOfHomePage/>
        <NavBar navigationData={navigationData}/>
        <AuthProvider>
        {children}
        </AuthProvider>
        </body>
    </html>
  );
}
